# Generated by Django 5.1.4 on 2025-01-18 15:05

import django.core.validators
import django.utils.timezone
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day_of_month', models.IntegerField(default=main.models.Meal.get_next_day, validators=[django.core.validators.MinValueValidator(1, message='Day must be at least 1'), django.core.validators.MaxValueValidator(31, message='Day cannot exceed 31')], verbose_name='日號')),
                ('breakfast_menu', models.TextField(blank=True, verbose_name='早餐')),
                ('lunch_menu', models.TextField(blank=True, verbose_name='午餐')),
                ('teatime_menu', models.TextField(blank=True, verbose_name='茶點')),
                ('dinner_menu', models.TextField(blank=True, verbose_name='晚餐')),
            ],
            options={
                'verbose_name': 'Meal',
                'verbose_name_plural': 'Meal',
                'db_table': 'meal',
                'ordering': ['day_of_month'],
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('Bed', '床位'), ('Others', '其他')], default='Bed', max_length=10, verbose_name='類別')),
                ('description', models.TextField(verbose_name='描述')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='價格')),
            ],
            options={
                'verbose_name': 'Price',
                'verbose_name_plural': 'Price',
                'db_table': 'price',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('age', models.PositiveIntegerField(blank=True)),
                ('job_title', models.CharField(max_length=200)),
                ('job_duties', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('home_address', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('hire_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('staff_type', models.CharField(choices=[('General', 'General'), ('Specialist', 'Specialist')], default='General', max_length=10)),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staff',
                'db_table': 'staff',
            },
        ),
    ]
