# Generated by Django 5.1.4 on 2025-01-14 08:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='user',
        ),
        migrations.AlterField(
            model_name='meal',
            name='setup_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Meal Date'),
        ),
    ]
