# Generated by Django 5.1.4 on 2025-01-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_staff_age_alter_staff_job_duties_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='home_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
